name: Keep Render Alive (Simple)

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
    - name: Ping Render Service
      run: |
        echo "🌐 Pinging Render service..."
        
        # Simple ping with retries
        for i in {1..3}; do
          echo "🔄 Attempt $i of 3..."
          
          if curl -s --max-time 20 --connect-timeout 10 \
             "https://shaadi-mantrana.onrender.com/health" > /dev/null; then
            echo "✅ Service is alive!"
            exit 0
          else
            echo "⚠️  Attempt $i failed"
            if [ $i -lt 3 ]; then
              echo "⏳ Waiting 5 seconds..."
              sleep 5
            fi
          fi
        done
        
        echo "❌ All attempts failed"
        exit 1
